_wandb:
    value:
        cli_version: 0.22.0
        e:
            5xug0j7mzl4f6vj7pi9c0zgki2hc0nyc:
                codePath: OneDrive\Desktop\DATA-SCIENCE-PROJECT\src\main.ipynb
                codePathLocal: main.ipynb
                cpu_count: 2
                cpu_count_logical: 2
                disk:
                    /:
                        total: "126701789184"
                        used: "112790413312"
                email: ajheshbasnet@gmail.com
                executable: c:\Users\hp\OneDrive\Desktop\DATA-SCIENCE-PROJECT\venv\Scripts\python.exe
                git:
                    commit: 8c43648a31f3d3415cf41326858899e4f6f029fd
                    remote: https://gitlab.com/ajheshbasnet/cicd-pipelines.git
                host: Ajhesh
                memory:
                    total: "4157509632"
                os: Windows-10-10.0.19045-SP0
                program: c:\Users\hp\OneDrive\Desktop\DATA-SCIENCE-PROJECT\src\main.ipynb
                python: CPython 3.13.3
                root: c:\Users\hp\OneDrive\Desktop\DATA-SCIENCE-PROJECT\src
                startedAt: "2025-09-20T05:50:27.287017Z"
                writerId: 5xug0j7mzl4f6vj7pi9c0zgki2hc0nyc
        m: []
        python_version: 3.13.3
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.13.3
            "5": 0.22.0
            "8":
                - 1
                - 3
            "12": 0.22.0
            "13": windows-amd64
C:
    value: 1
max_iter:
    value: 100
penalty:
    value: l2
random_state:
    value: 42
solver:
    value: liblinear
